import type { ComponentProps } from 'react';
import {
  Archive,
  ArrowRight,
  Bed,
  Binoculars,
  Bus,
  CalendarDays,
  Car,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  Clock3,
  Download,
  FileText,
  Footprints,
  Hotel,
  Info,
  Luggage,
  Map,
  LogOut,
  Moon,
  Mountain,
  EllipsisVertical,
  Plane,
  Plus,
  Route,
  Ship,
  Shuffle,
  TrainFront,
  Trash2,
  TriangleAlert,
  Utensils,
  Users,
  Wine,
  X,
  type LucideIcon,
} from 'lucide-react';

type TripIconProps = Omit<ComponentProps<LucideIcon>, 'ref'> & {
  name?: string | null;
};

const ICONS: Record<string, LucideIcon> = {
  archive: Archive,
  arrowright: ArrowRight,
  'arrow-right': ArrowRight,
  back: ChevronLeft,
  bed: Bed,
  binoculars: Binoculars,
  bus: Bus,
  calendar: CalendarDays,
  car: Car,
  check: Check,
  chevron: ChevronRight,
  clock: Clock3,
  doc: FileText,
  download: Download,
  ferry: Ship,
  flight: Plane,
  footprints: Footprints,
  fork: Utensils,
  hotel: Hotel,
  info: Info,
  luggage: Luggage,
  logout: LogOut,
  map: Map,
  more: EllipsisVertical,
  moon: Moon,
  mountain: Mountain,
  plane: Plane,
  plus: Plus,
  route: Route,
  ship: Ship,
  shuffle: Shuffle,
  train: TrainFront,
  trash: Trash2,
  utensils: Utensils,
  users: Users,
  walk: Footprints,
  warning: TriangleAlert,
  wine: Wine,
  x: X,
};

export function TripIcon({ name, 'aria-hidden': ariaHidden = true, ...props }: TripIconProps) {
  const Icon = ICONS[name?.trim().toLowerCase() || ''] ?? CircleHelp;

  return <Icon aria-hidden={ariaHidden} {...props} />;
}
